version: '3.9'
services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    environment:
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASS: ${MYSQL_ADMIN_PASS}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PS: ${WP_ADMIN_PS}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${MYSQL_DB}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PS: ${WP_USER_PS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
    networks:
      - internal
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html
    ports:
      # - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - wordpress
    restart: always
    

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASS: ${MYSQL_ADMIN_PASS}
      MYSQL_DB: ${MYSQL_DB}
    restart: always

networks:
  internal:
      driver: bridge


volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/ybentaye/data/mariadb"
  wordpress-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/ybentaye/data/wordpress"

